haiwen/seafile-docs

- deploy/using_mysql.md
> fixed granting access to newly created seafile mysql user

- deploy/deploy_with_apache.md
Without this addition on my Apache2.2, I had permission problems:
`client denied by server configuration: proxy:http://127.0.0.1:8082/upload-aj/51`
> Another addition concerning Apache2.2

- develop/web_api.md
change to English single quotes
> add request parameters of libraries search

- build_seafile/osx.md
This should closes haiwen/seafile#1100
> improve the document of mac osx

- deploy/https_with_nginx.md
I think thats some default security settings which should be noticed.
> add additional optional security settings for nginx

- develop/web_api.md
add 'reuse' argument to control if reuse file server access token for download file
> update doc of download file api

- develop/web_api.md
add 't' argument to control only return file or dir entries.
add 'recursive_dir' argument to control If return recursive dir list.
> update doc of get dir entry api

- deploy_pro/deploy_in_a_cluster.md
> haproxy: non-deprecated timeout settings

- deploy_windows/deploy_with_mysql.md
* removed pro edition config because it confuses most user
* increased comprehensibility for average users
> improved comprehensibility

- SUMMARY.md
- develop/README.md
Hello, I have added a link to a PHP API implementation of the Seafile Web API. Just that, nothing else.
Regards
> added link to PHP API implementation

- deploy_pro/upgrade_a_cluster.md
> add cluster upgrade document 4.4 -> 5.0

- deploy/using_ldap.md
Fixed some small typos and (subjectively) made some explanations a little bit more clear.
> Improve spelling and grammar of LDAP doc

- deploy/deploy_seahub_at_non-root_domain.md
> non root deploy doc fix wrt issue 1186

- build_seafile/linux.md
Also removed unnecessary requirements for fuse pkgs.
> Updated linux build doc to use support qt5

- build_seafile/server.md
- config/ccnet-conf.md
- config/quota_and_size_options.md
- config/seafile-conf.md
- config/seahub_settings_py.md
- config/sending_email.md
- deploy/deploy_seahub_at_non-root_domain.md
- deploy/deploy_with_apache.md
- deploy/deploy_with_nginx.md
- deploy/https_with_nginx.md
- deploy/server.md
- deploy/server_configuration.md
- deploy/upgrade.md
- deploy/upgrade_with_mysql_or_postgresql.md
- deploy/using_fuse.md
- deploy/using_mysql.md
- deploy_windows/deploy_with_apache.md
- deploy_windows/deploy_with_nginx.md
- develop/env.md
- extension/fuse.md
- extension/webdav.md
- faq.md
Language, appearance and content improvements.
> Improvements 160524

- build_seafile/linux.md
> added libcurl-devel to list of dependencies for Fedora

- extension/webdav.md
> Update webdav.md with nginx timeout settings

- deploy/upgrade.md
Update upgrade.md to latest server version. Commited it in Jan 2016 already, but didn't request a pull, sry. Updated it now and it should be ready!
> Update upgrade.md to latest server version

- maintain/seafile_gc.md
Moved comment line up in script.
> Corrected comment line section in seafile_gc.md

- develop/web_api_v2.1.md
add sample request/response when get recursive dir list of a folder
> update api v2.1

- develop/web_api_v2.1.md
1. add docs of revert folder from repo trash
1. add docs of restore file from history
> update web api

- develop/web_api_v2.1.md
add `ret-json` parameter for return uploaded file info
> update upload file api

- develop/web_api_v2.1.md
return obj info when copy/move file via web api in bulk
> update file ops api

- develop/web_api_v2.1.md
1. add repo history api.
1. add repo trash api.
1. udpate search file api, add 'content_highlight' to search result
> udpate web api v2.1

- develop/web_api_v2.1.md
add docs of batch share repos to user/group
> update docs of web api v2.1

- deploy/only_office.md
Added full guide with many external references.
This guide allows to deploy the OnlyOffice document server locally via a subfolder.
Please publish so we can discuss with the community further about it.
> Huge update of only_office.md

- develop/web_api_v2.1.md
add `action` parameter for get owa file info
> update doc of web api v2.1

- deploy/https_with_nginx.md
server_tokens off;
See:
https://forum.seafile.com/t/nginx-did-i-miss-something-in-the-config-file/3077/5
> Minor security fix

- config/seahub_settings_py.md
- deploy/video_thumbnails.md
Also changed link in config file to point to that file.
> Created manual for video thumbnails

- deploy/start_seafile_at_system_bootup.md
See https://forum.seafile.com/t/autostart-script/3167/2
Changed the order of systemd to the front because it is used by most distributions by now incl. Ubuntu 16.04).
Changed Ubuntu to Ubuntu 14.10 and older.
Made a few little changes (not in the script code).
> Cleaned up, changed order

- deploy/add_memcached.md
- deploy_pro/deploy_in_a_cluster.md
although it is already fixed I mention it here so it'll be closed.
fixes #226
> minor language improvements for memcached setup

- deploy_pro/clustering_with_mariadb_ceph.md
See also commit message for changes.
I've done most of the changes within the last year. A part that needs to improved even after this PR is that some information is outdated.
> Deploy ceph improvements.

- deploy/using_logrotate.md
> improve log rotation documentation

- deploy/upgrade.md
- deploy/upgrade_notes.md
Files are in the same folder, no different path.
> Fixed links

- deploy/only_office.md
Apache needs further testing, but config can be publish. It is marked as beta.
Some users asked for it.
> OnlyOffice: Added notes regarding subfolder, updated config and added beta apache config

- develop/web_api_v2.1.md
add comment for using fileserver download link
> update docs of admin share link download

- deploy/libreoffice_online.md
Adding odt and odp to the ods Open Document Formats that are supported viewing and editing via Libreoffice Online
> More Open Document Formats

- maintain/seafile_gc.md
> Fixed Typo

- deploy_pro/deploy_in_a_cluster.md
- deploy_pro/enable_search_and_background_tasks_in_a_cluster.md
add the final configuration of cluster.
> Explain cluster confs

- deploy_pro/deploy_in_a_cluster.md
- deploy_pro/enable_search_and_background_tasks_in_a_cluster.md
- Update enable_search_and_background_tasks_in_a_cluster.md
- Update deploy_in_a_cluster.md
> Fix ElasticSearch port

- deploy/https_with_nginx.md
> Tiny update https_with_nginx.md

- deploy/deploy_with_nginx.md
- deploy/https_with_nginx.md
This reverts commit 521bc303392612f4f85d97c246766e74ec99aac3.
> Revert "update the config of nginx_wsgi_proxy"

- develop/web_api_v2.1.md
1. search file from mine/shared/group/public libraries.
2. add directory detail api.
> update seahub web api

- develop/web_api.md
Fixed typo in "Sample request"  for Download Directory
> Fixed typo in directory downloading sample

- develop/web_api_v2.1.md
add description for `ftype` parameter.
> update doc for file search api

- deploy/upgrade.md
fixes #451
and includes some additional improvements.
> Upgrade instruction improvements

- deploy/using_sqlite.md
> install python-requests

- deploy/add_memcached.md
> memcached: improve python header file install

- changelog.md
> link android and ios client changelogs

- maintain/account.md
Added the line so people know that there data on the Admin account 'll not get deleted as the word reset can mean that everything get's back to zero.
> Added information regarding reset-admin.sh

- deploy_pro/download_and_setup_seafile_professional_server.md
1, Remove support for Ubuntu 14.04
1, Explain using different compiled tar.gz file on different Linux distribution
> update docs of download/setup pro serve

- deploy/oauth.md
With the gaining popularity after the m$ incident it might be useful to help Gitlab users to get started.
> Add a sample for gitlab users

- maintain/seafile_gc.md
https://github.com/haiwen/seafile-docker/issues/66 and https://github.com/haiwen/seafile-docker/issues/71
> Notes for GC in a docker container

- develop/web_api_v2.1.md
1, admin set group quota
2, add/delete group owned repo
3, modify group owned sub folder permission
> add group owned library docs

- develop/web_api_v2.1.md
> update docs of share library

- config/seafile-conf.md
Following https://github.com/haiwen/seafile-server/issues/167#issuecomment-403554578
> Add seafile database configuration section

- develop/web_api_v2.1.md
add last modifier and upload info
> update docs of file detail api

- config/seahub_settings_py.md
delete account/change login password/update basic user info
> add seahub settings configration

- deploy_pro/deploy_in_a_cluster.md
There were typos in the links.
> Correct links of Backend Storage in Cluster Deploy
