deploy/deploy_Seahub_at_Non-root_domain.md

Hi
This patch suggests that a user should clear the cache when the directory of seafile on the webserver has changed, to that all links to the old directory location that are still stored in the cache should be updated. It should prevent what was reported in:
https://github.com/haiwen/seafile/issues/355

Suggest to clear the cache when the seafile directory has changed.

---

deploy/deploy_http_sync.md

Added information on how to configure the webserver with full
certificate chain to let the Seafile client to work without
any change in settings.

HTTPS sync using full certificate chains

---

deploy_pro/enable_search_and_background_tasks_in_a_cluster.md

Poppler is needed for pdf text extraction at the background node.

deploy_pro/search_and_background: poppler needed

---

deploy_pro/enable_search_and_background_tasks_in_a_cluster.md

At least during my tests I needed to start seahub as well to get a working background node.

deploy_pro/search_and_background: start seahub

---

deploy/deploy_seahub_at_non-root_domain.md

Several people had problems with the hardcoded /seafhttp file server path. This change clarifies the issue when deploying seafile for a non-root domain: https://github.com/haiwen/seafile/issues/1224

Clarified hardcoded /seafhttp path for non-root deployment

---

deploy/shibboleth_config.md

Shibboleth.sso is for receiving answers from identity provider. You
can't protect shibboleth with shibboleth.
Another configuration error combined with this misconfiguration made me
DoS my identity provider (error answer creates new request, redirect
loop in browser).
Furthermore I needed to prevent Apache from sending Shibboleth.sso requests
to seafile. It's not of its business.
Fixes #101

Fix for Shibboleth config example

---

deploy/using_sqlite.md

> The Seafile server package requires the following packages have been installed in your system
Does it still work with python 2.6.5+? There was some discussion on the forums. Unfortunately I can't currently find the link
- Consistent use of Seafile and Seahub
- Some language improvements (at least I think those are improvements ;))

optimisations

---

deploy/using_ldap.md
deploy_pro/using_ldap_pro.md

If the system's LDAP libs are to be used, the Seafile-packaged ldap libs have to be (re)moved after every upgrade.
This is easy to forget. Together with my previous commits this completely replaces haiwen/seafile-docs#123 (which can therefore be closed without merging)

Clarify: ldap libs need to be moved every upgrade

---

deploy/deploy_with_apache.md

The references show that there was a bug before Apache 2.4.10 leading to the wrong behaviour. As there were many reports I think this note is helpful.
References
* https://github.com/haiwen/seafile/issues/1258#issuecomment-188866740
* https://bugs.launchpad.net/ubuntu/+source/apache2/+bug/1284641
* https://bugs.launchpad.net/ubuntu/+source/apache2/+bug/1284641/comments/5

Added hint for problems with spaces using Apache 2.4.7

---

SUMMARY.md
deploy_windows/deploy_with_windows.md
deploy_windows/windows_fsck.md

Documented the basic syntax to run seaf-fsck while in a Windows environment (as pointed out by *Jia Qiang Xu* in thread: [Error running seaf-fsck on Windows Server](https://forum.seafile-server.org/t/error-running-seaf-fsck-on-windows-server/4570)).
Feel free to notify me of needed corrections.

Added information on how to run seaf-fsck.exe under Windows.

---

deploy/deploy_with_nginx.md

I fixed wrong nginx folder names: ``sites-enabled``and ``sites-available`` instead of ``site-enabled``and ``site-available``.

fixing typos in "Config Seahub with Nginx"

---

deploy_pro/real_time_backup.md

Shouldn't it be log_bin? It is the default in /etc/mysql/my.cnf on Debian. Also see: http://dev.mysql.com/doc/refman/5.7/en/replication-options-binary-log.html

log_bin instead of log-bin

---

security/fail2ban.md

Created the fail2ban manual which was missing from the main manual repository for quiet a while.
Cloned from https://github.com/DenisChatenay/seafile-authentication-fail2ban
'DenisChatenauy' didn't want to clone it himself (no time I guess), hence I did it as it was overdue.
Thanks for merging!

Added fail2ban security manual

---

deploy_pro/details_about_file_search.md

The config `external_es_server` need to be to use an external elasticsearch server. It's described in the docs about "running in a cluster", but missing in `details_about_file_search.md` .

Fixed the missing part in "using external elasticsearch server".

---

deploy/using_mysql.md

The double `-t` is obviously wrong (and produces an error like `xyz is not a valid port`). I found the actual flag `-r` in `setup-seafile-mysql.py`.

Fix wrong flag for setting MYSQL_ROOT_PASSWD in auto setup mode

---

deploy/using_postgresql.md

Due to missing environment variable, importer tries to get ccnet.conf from  unable to apply migrations (ccnet), but it actually placed in conf/ dir, which should be in SEAFILE_CENTRAL_CONF_DIR variable

Missing export

---

deploy/server_configuration.md

Added a short summary of documentation about undocumented variables but also a link to the more in-depth documentation in django email doc.
Also please note that `EMAIL_HOST_USER` is not **necessary** an email address eg `user@domain`. It could just be as well be simply `user`. That's why I modified this a bit.

Add link to django documentation for email variables

---

deploy/https_with_nginx.md

Default settings only get a C rating at SSL Labs and contain serious problems.
Of course everyone is responsible for themselves. But we could guide them in the right direction.
I forgot to mention: This is not compatible with: "IE 6 / XP" and "IE 8 / XP". But I surely can live with that. XP is unsupported by Microsoft!
closes #98 
This is a rebased version of #98 from @egroeper am going to work on another update once this has been merged. Am also going to address the to points above there.

Nginx with secure SSL settings

---

deploy/upgrade_notes.md

See also https://forum.seafile.com/t/upgraded-with-wrong-architecture-debian-32bit-community-edition-fixed-it-now-i-cant-upgrade-to-6-1-1/3227/22?u=shoeper

add that python-requests is required in some cases

---

deploy_pro/office_documents_preview.md

also fixes https://www.gitbook.com/book/seafile/seafile-server-manual/discussions/5
One remaining question is whether this is still the case:
> Current office online preview works with libreoffice 4.0-4.2

fix links to libreoffice

---

deploy/https_with_nginx.md

Added "always" in the end of the add_header Strict-Transport-Security as according to NGINX it should be always there to bee more secure.

added "always" to add_header Strict-Transport-Security

---

maintain/seafile_gc.md

In the GC script for the CE version I did add so it also starts and stops seahub.service and I did increase the sleep time to 20 and 10 seconds.
It's needed because otherwise it will cause a error in seahub_django_request.log and that's because in the previous script it never did shutdown seahub.service it did only shutdown seafile.service.

Fixed a bug that did cause error logs.

---

security/fail2ban.md

Added that you need to change the time zone to get fail2ban to work.
Also added clarifications regarding how fail2ban will ban failed login attempts, it's needed as it was not clear as fail2ban state maxretry3 but in fact it's 9 attempt's as seahub.log create a line every 3 failed attempts.

Added fix for the fail2ban to work.

---

maintain/seafile_gc.md

I did delete the "-r" in the end of this line: sudo -u seafile $pathtoseafile/seafile-server-latest/seaf-gc.sh
If you run it with the "-r" in the end of the line it don't clean up, but if you run with without the -r then it works correctly.
It has been reported in the forum and also I have tried it by my self and I can confirmed that it works without the -r

Fixed a the GC script.

---

develop/web_api_v2.1.md

In the examples the wrong parameter name is used.

Fix share folder examples

---

deploy/start_seafile_at_system_bootup.md
deploy_pro/enable_search_and_background_tasks_in_a_cluster.md

From https://www.freedesktop.org/software/systemd/man/systemd.service.html#Type=:
> If set to forking, it is expected that the process configured with ExecStart= will call fork() as part of its start-up. The parent process is expected to exit when start-up is complete and all communication channels are set up. The child continues to run as the main daemon process. This is the behavior of traditional UNIX daemons. If this setting is used, it is recommended to also use the PIDFile= option, so that systemd can identify the main process of the daemon. systemd will proceed with starting follow-up units as soon as the parent process exits.

Set systemd service type to forking

---

deploy/using_mysql.md

If a user wishes to install following these instructions and does not setup nginx/apache, then they will not be able to access the web interface.  If you follow the current instructions you will get an HTTP 500 error when loading the seafile webui at HOSTNAME:8000, this is because there is no webserver installed, not even a minimal one like python-requests.  I propose that following the barebones instructions should install at least a minimal webui.

add python-requests dependency for basic webserver

---

deploy/deploy_seahub_at_non-root_domain.md
deploy/deploy_with_apache.md
deploy/https_with_apache.md
deploy/only_office.md
deploy/shibboleth_config.md
deploy/shibboleth_config_v6.3.md
deploy_windows/deploy_with_apache.md
extension/webdav.md

This ensures that Django in Seahub behind the Proxy will see the correct
Host header for incoming requests and - in turn - render correct results
for `request.build_absolute_uri`.
Without this directive, no avatars are rendered on user search for sharing a library.

Add ProxyPreserveHost On to Apache config blocks
